"""empty message

Revision ID: 011e1ea78393
Revises: 9858b711820e
Create Date: 2016-10-14 09:52:59.477440

"""

# revision identifiers, used by Alembic.
revision = '011e1ea78393'
down_revision = '9858b711820e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.drop_column('vote_count')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vote_count', sa.INTEGER(), nullable=True))

    ### end Alembic commands ###
