"""empty message

Revision ID: 0c8b4adb6020
Revises: 347f4ec5eb5e
Create Date: 2016-10-12 15:28:01.026246

"""

# revision identifiers, used by Alembic.
revision = '0c8b4adb6020'
down_revision = '347f4ec5eb5e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_name', ['name'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_name', type_='unique')

    ### end Alembic commands ###
