"""empty message

Revision ID: 1a7dfd455444
Revises: 011e1ea78393
Create Date: 2016-10-14 09:53:26.899981

"""

# revision identifiers, used by Alembic.
revision = '1a7dfd455444'
down_revision = '011e1ea78393'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vote_count', sa.Integer(), default=0))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.drop_column('vote_count')

    ### end Alembic commands ###
