"""empty message

Revision ID: 2f19a137d6e6
Revises: 23e40b9b14f9
Create Date: 2017-01-12 00:09:49.580585

"""

# revision identifiers, used by Alembic.
revision = '2f19a137d6e6'
down_revision = '23e40b9b14f9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.String(length=60), nullable=True))
        batch_op.create_unique_constraint('unique_client_id', ['client_id'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('unique_client_id', type_='unique')
        batch_op.drop_column('client_id')

    ### end Alembic commands ###
