"""empty message

Revision ID: 3c373ee3a69a
Revises: 682fa0321a3e
Create Date: 2016-12-17 13:04:12.875717

"""

# revision identifiers, used by Alembic.
revision = '3c373ee3a69a'
down_revision = '682fa0321a3e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_polls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_identifier', sa.String(length=100), nullable=True))
        batch_op.drop_constraint('user_foreign_key', type_='foreignkey')
        batch_op.drop_column('user_id')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_polls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('user_foreign_key', 'users', ['user_id'], ['id'])
        batch_op.drop_column('user_identifier')

    ### end Alembic commands ###
