"""empty message

Revision ID: 682fa0321a3e
Revises: 20a1622bf8e4
Create Date: 2016-11-27 02:12:21.539233

"""

# revision identifiers, used by Alembic.
revision = '682fa0321a3e'
down_revision = '20a1622bf8e4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('close_date', sa.DateTime(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_column('close_date')

    ### end Alembic commands ###
