"""empty message

Revision ID: 9858b711820e
Revises: 0c8b4adb6020
Create Date: 2016-10-12 23:28:39.773300

"""

# revision identifiers, used by Alembic.
revision = '9858b711820e'
down_revision = '0c8b4adb6020'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_foreign_key('user_foreign_key', 'users', ['create_uid'], ['id'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_constraint('user_foreign_key', type_='foreignkey')

    ### end Alembic commands ###
