"""empty message

Revision ID: a6a076719bb6
Revises: 2170aeece555
Create Date: 2017-01-30 00:50:48.143646

"""

# revision identifiers, used by Alembic.
revision = 'a6a076719bb6'
down_revision = '682fa0321a3e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_id', sa.String(length=11), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_column('unique_id')

    ### end Alembic commands ###
